- name: Run kubeadm join
  command: |
    kubeadm join \
    --token {{ kubeadm_token }} \
    {{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}
  become: yes
  args:
    creates: /etc/kubernetes/kubelet.conf
