- name: install docker binaries
  shell: |
    cp /tmp/docker-{{ docker_version }}/docker/docker* /usr/bin/
  become: yes

- name: restart docker
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted
  become: yes
