- name: create /tmp/etcd-{{ etcd_version }}
  file:
    dest: "/tmp/etcd-{{ etcd_version }}"
    state: directory
  tags:
    - install

- name: download etcd binary
  unarchive:
    src: "{{ etcd.download_url }}"
    dest: "{{ etcd.download_dest }}"
    remote_src: yes
    creates: "{{ etcd.download_dest }}/etcd-v{{ etcd_version }}-linux-amd64"
  notify:
    - etcd-install-bin
  tags:
    - install

- name: install etcd binaries
  shell: |
    cp {{ etcd.download_dest }}/etcd-v{{ etcd_version }}-linux-amd64/etcd* /usr/bin/
  args:
    creates: /usr/bin/etcd
  become: yes

- name: create {{ etcd.data_dir }}
  file:
    dest: "{{ etcd.data_dir }}"
    state: directory
  become: yes
  tags:
    - install
