etcd_version: 3.1.0
etcd:
  download_url: https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
  download_dest: /tmp/etcd-{{ etcd_version }}
  advertise_url: "{{ ansible_default_ipv4.address }}"
  data_dir: /var/lib/etcd
