- include: tls.yml
- name: create /etc/kubernetes/manifests
  file:
    dest: /etc/kubernetes/manifests
    state: directory
  become: yes

- name: template kubeconfig.yml
  template:
    src: kubeconfig.yml
    dest: /etc/kubernetes/kubeconfig.yml
  become: yes

- name: template kube-apiserver.yml
  template:
    src: kube-apiserver.yml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.yml
  become: yes

- name: template kube-proxy.yml
  template:
    src: kube-proxy.yml.j2
    dest: /etc/kubernetes/manifests/kube-proxy.yml
  become: yes

- name: template kube-controller-manager.yml
  template:
    src: kube-controller-manager.yml.j2
    dest: /etc/kubernetes/manifests/kube-controller-manager.yml
  become: yes

- name: template kube-scheduler.yml
  template:
    src: kube-scheduler.yml.j2
    dest: /etc/kubernetes/manifests/kube-scheduler.yml
  become: yes

- name: template kube-dns.yml
  template:
    src: kube-dns.yml.j2
    dest: /etc/kubernetes/manifests/kube-dns.yml
  become: yes

- name: template kubelet.service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  become: yes
  notify:
    - restart kubelet

- name: enable/start kubelet.service
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
